#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Denne kode blev oprettet ved hjælp af et værktøj.
//     Runtime-version:4.0.30319.18444
//
//     Ændringer af denne fil kan resultere i ukorrekt funktion, og ændringerne mistes, hvis
//     koden oprettes igen.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Glubenheim.Resource", IsApplication=true)]

namespace Glubenheim
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Avatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Avatar_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Avatar_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int custom_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int splash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000b
			public const int item1 = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int item2 = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int item3 = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int myButton1 = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int myButton2 = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int myButton3 = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int myButton4 = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int myButtonL2_1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int myButtonL2_2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int myButtonL2_3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int myButtonL2_4 = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int myImageButton = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int popupButton = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int popupButtonL2 = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Layout2 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int popup_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
