#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Glubenheim.Resource", IsApplication=true)]

namespace Glubenheim
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AButton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AButtonP = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AButtonXML = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int B1Button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int B1ButtonP = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int B1ButtonXML = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int B2Button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int B2ButtonP = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int B2ButtonXML = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BButton = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int BButtonP = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int BButtonXML = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ClearButton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ClearButtonP = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ClearButtonXML = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int DownButton = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int DownButtonP = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int DownButtonXML = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int HelpButton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int HelpButtonP2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int HelpButtonXML = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int LayoutButton = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int LayoutButtonP = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int LayoutButtonXML = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int LeftButton = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int LeftButtonP = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int LeftButtonXML = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int LeftMouse = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int LeftMouseP = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int LeftMouseXML = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int MidButton = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int MidButtonP = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int MidButtonXML = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int MousePad = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int RightButton = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int RightButtonP = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int RightButtonXML = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int RightMouse = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int RightMouseP = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int RightMouseXML = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Select1 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Select1P = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int SelectButtonXML = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int SendButton = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int SendButtonP = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int SendButtonXML = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int splash = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int StartButton1 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int StartButton1P = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int StartButtonXML = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int UpButton = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int UpButtonP = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int UpButtonXML = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int XButton = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int XButtonP = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int XButtonXML = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int YButton = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int YButtonP = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int YButtonXML = 2130837563;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070007
			public const int AButton = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int BButton = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int Bumper1Button = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int Bumper2Button = 2131165196;
			
			// aapt resource value: 0x7f070015
			public const int ClearButton = 2131165205;
			
			// aapt resource value: 0x7f070003
			public const int DownButton = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int Help = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int HelpButton = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int LeftButton = 2131165186;
			
			// aapt resource value: 0x7f070011
			public const int MLeftButton = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int MMidButton = 2131165200;
			
			// aapt resource value: 0x7f070012
			public const int MRightButton = 2131165202;
			
			// aapt resource value: 0x7f070005
			public const int PopUp = 2131165189;
			
			// aapt resource value: 0x7f070001
			public const int RightButton = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int SelectButton = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int SendButton = 2131165204;
			
			// aapt resource value: 0x7f070009
			public const int StartButton = 2131165193;
			
			// aapt resource value: 0x7f07000f
			public const int TouchPad = 2131165199;
			
			// aapt resource value: 0x7f070000
			public const int UpButton = 2131165184;
			
			// aapt resource value: 0x7f07000e
			public const int XButton = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int YButton = 2131165197;
			
			// aapt resource value: 0x7f070013
			public const int eText = 2131165203;
			
			// aapt resource value: 0x7f070016
			public const int item1 = 2131165206;
			
			// aapt resource value: 0x7f070017
			public const int item2 = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int item3 = 2131165208;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int LLO1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LLO2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LLO3 = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int popup_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
